name: Generate API Documentation

on:
  # Run manually from the Actions tab
  workflow_dispatch:
  # Run on push to main branch (uncomment if desired)
  # push:
  #   branches: [ main ]
  # Run on schedule (weekly on Sunday at midnight)
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml
          tools: composer

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install html2text

      - name: Download phpDocumentor
        run: |
          curl -LO https://phpdoc.org/phpDocumentor.phar
          chmod +x phpDocumentor.phar

      - name: Generate Documentation
        run: |
          php phpDocumentor.phar -c phpdoc-simple.xml
          python html2md.py docs/reference
          find docs/reference -name "*.html" -delete

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add docs/reference
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update API documentation" && git push)
