name: Generate WordPress Hook Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  document:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          
      - name: Initialize Composer
        run: |
          composer init --no-interaction --name=dennisdornon/doc-test
        
      - name: Install wp-documentor
        run: |
          composer require pronamic/wp-documentor --dev
          
      - name: Generate Hook Documentation
        run: |
          mkdir -p docs
          ./vendor/bin/wp-documentor hooks --source=. --output=./docs/hooks.md || true
          ./vendor/bin/wp-documentor filters --source=. --output=./docs/filters.md || true
          ./vendor/bin/wp-documentor actions --source=. --output=./docs/actions.md || true
          
      - name: List generated files
        run: |
          ls -la docs/
          
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update WordPress hook documentation
          file_pattern: docs/*.md
