name: Generate WordPress Hook Documentation

on:
  workflow_dispatch:

jobs:
  document:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          
      - name: Install wp-documentor
        run: |
          composer require pronamic/wp-documentor --dev
          
      - name: Show wp-documentor commands
        run: |
          ./vendor/bin/wp-documentor list
          
      - name: Generate documentation
        run: |
          mkdir -p docs
          # Add exactly the command you use locally here
          ./vendor/bin/wp-documentor hooks --source=. --output=./docs/hooks.md
          
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update WordPress hook documentation
          file_pattern: docs/*.md
